// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3dFYko6IG5tHNFPl7dlUUDs3fkJDPSmA',
    appId: '1:253123004666:web:ca16dd261d812e081ee143',
    messagingSenderId: '253123004666',
    projectId: 'image-pictured-x-firebase',
    authDomain: 'image-pictured-x-firebase.firebaseapp.com',
    storageBucket: 'image-pictured-x-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7TiWJjPKL081osQAm8TNybarIK38Hps8',
    appId: '1:253123004666:android:23924d0762d141d91ee143',
    messagingSenderId: '253123004666',
    projectId: 'image-pictured-x-firebase',
    storageBucket: 'image-pictured-x-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ75K6sx3_UZYiWcxf4MUD9RlrJF4hZBQ',
    appId: '1:253123004666:ios:24ac07784fc1849e1ee143',
    messagingSenderId: '253123004666',
    projectId: 'image-pictured-x-firebase',
    storageBucket: 'image-pictured-x-firebase.appspot.com',
    iosClientId: '253123004666-9qn4s0fj38jcojmd8si79ucfo2287f5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.filePikerStorageFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ75K6sx3_UZYiWcxf4MUD9RlrJF4hZBQ',
    appId: '1:253123004666:ios:24ac07784fc1849e1ee143',
    messagingSenderId: '253123004666',
    projectId: 'image-pictured-x-firebase',
    storageBucket: 'image-pictured-x-firebase.appspot.com',
    iosClientId: '253123004666-9qn4s0fj38jcojmd8si79ucfo2287f5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.filePikerStorageFirebase',
  );
}
